# -*- coding: utf-8 -*-
"""mathematicsProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQSiGsQeSeCB_ysDSFqhq8MyYsQM3Ee8
"""

# Import libraries
import numpy as np
import matplotlib.pyplot as plt
from numpy import random

# Generate a seed value for a random number of generator
random.seed(0)

# total indicates the total no of people is in each age range
total={20:0, 30:0, 40:0, 50:0, 60:0}
#purchases indicates the total no of purchases were made by each person in these age range
purchases={20:0, 30:0, 40:0, 50:0, 60:0}
# total number of purchases regardless of age
totalPurchases=0

# create a loop to iterate through 50000 radom people.
for _ in range(50000):
  ageDecade=random.choice([20, 30, 40, 50, 60])
  # Compute a purchase probability given by the age
  purchaseProbability=float(ageDecade) / 100.0
  # collect the total for the generated age decade
  total[ageDecade] +=1
  # check the person bought something if random number is less than the purchase probability
  if(random.random() < purchaseProbability):
    # total number of purchases that are done across the entire dataset
    totalPurchases +=1
    # track of purchases for the individual age decade
    purchases[ageDecade] +=1

total

purchases

totalPurchases

# barchart for total people in each age decade

plt.figure(figsize=(8, 6))
plt.bar(total.keys(), total.values())
plt.xlabel('Age Decade')
plt.ylabel('Total People')
plt.title('Total People in Each age Decate')
# ser x-axis ticks to only show the decades
plt.xticks(list(total.keys()))
plt.show()

# barchart for purchases made by each age decade

plt.figure(figsize=(8, 6))
plt.bar(total.keys(), purchases.values())
plt.xlabel('Age Decade')
plt.ylabel('Purchases Made')
plt.title('Purchases Made by Each age Decade')
# ser x-axis ticks to only show the decades
plt.xticks(list(purchases.keys()))
plt.show()

"""Conditional Probability"""

# compute P(A|B), where A is "purchase" and B is "the person in it's 50's"
PAB=float(purchases[50])/float(total[50])
print('P(purchase|50s): ' +str(PAB))

# compute P(B) means the probability of being 50 in the dataset
PB= float(total[50])/50000.0
print('P(50s): ' +str(PB))

# compute p(A) means the overall probability of buying something, regardless of its age
PA= float(totalPurchases)/50000.0
print('P(perchase): ' +str(PA))

#  P(A|B) = P(A,B)/ P(A)

# Compute P(A,B) where it is the probability of both being in its 50's and buying something P(A,B) out of the total population
print('P(50s, purchase ): ' +str(float(purchases[50]) / 50000.0))

# compute the overall probability of buying something and the overall probability of being in 50's
print('P(50s) P(purchase): ' +str(PA*PB))

# Compute P(A|B)
print((purchases[50]/50000.0) / PB)

"""Conditional Probabilities without Weighted Probabilities"""

# Import random from numpy package
from numpy import random

# Generate a seed value for a random number of generator
random.seed(0)

# total indicates that total no of people is in each age range
total={20:0, 30:0, 40:0, 50:0, 60:0}
#purchases indicates that total no of purchases were made by each person in these age range
purchases={20:0, 30:0, 40:0, 50:0, 60:0}
# total number of purchases regardless of age
totalPurchases=0

# create a loop to iterate through 50000 radom people.In a other word, for each of these 50000 people, the loop is iterated 50000 times and
#for each time, an age decate is assigned to the individual person.
for _ in range(50000):
  ageDecade=random.choice([20, 30, 40, 50, 60])
  # Compute a purchase probability given by the age
  purchaseProbability=0.3
  # collect the total for the generated age decade
  total[ageDecade] +=1
  # check the person bought something if random number is less than the purchase probability
  if(random.random() < purchaseProbability):
    # total number of purchases that are done across the entire dataset
    totalPurchases +=1
    # track of purchases for the individual age decade
    purchases[ageDecade] +=1

total

purchases

totalPurchases

# barchart for total people in each age decade

plt.figure(figsize=(8, 6))
plt.bar(total.keys(), total.values())
plt.xlabel('Age Decade')
plt.ylabel('Total People')
plt.title('Total People in Each age Decate')
# ser x-axis ticks to only show the decades
plt.xticks(list(total.keys()))
plt.show()

# barchart for purchases made by each age decade

plt.figure(figsize=(8, 6))
plt.bar(total.keys(), purchases.values())
plt.xlabel('Age Decade')
plt.ylabel('Purchases Made')
plt.title('Purchases Made by Each age Decade')
# ser x-axis ticks to only show the decades
plt.xticks(list(purchases.keys()))
plt.show()

PAB=float(purchases[50])/float(total[50])
print('P(purchases|50s): ' +str(PAB))

# Compute P(A)
PA=float(totalPurchases)/50000.0
print('P(purchases): ' +str(PA))